version: '3'
services:
  minio:
    image: minio/minio:RELEASE.2020-07-02T00-15-09Z
    ports:
      - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data1
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    depends_on:
        - minio
    ports:
      - "8000:8000"
volumes:
  pg_data: {}
  minio-data-1: