# Generated by Django 3.1.5 on 2021-01-12 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0001_inital_base_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='movies.movie'),
        ),
        migrations.AlterField(
            model_name='score',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_score', to=settings.AUTH_USER_MODEL),
        ),
    ]
