# Generated by Django 3.1.5 on 2021-01-27 16:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_add_some_fields_to_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='budget',
            field=models.IntegerField(default=1000, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actors', to='movies.movie')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actor_in_movies', to='movies.person')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='composers',
            field=models.ManyToManyField(related_name='composed_movies', to='movies.Person'),
        ),
        migrations.AddField(
            model_name='movie',
            name='directors',
            field=models.ManyToManyField(related_name='directed_movies', to='movies.Person'),
        ),
        migrations.AddField(
            model_name='movie',
            name='editors',
            field=models.ManyToManyField(related_name='edited_movies', to='movies.Person'),
        ),
        migrations.AddField(
            model_name='movie',
            name='operators',
            field=models.ManyToManyField(related_name='operated_movies', to='movies.Person'),
        ),
        migrations.AddField(
            model_name='movie',
            name='producers',
            field=models.ManyToManyField(related_name='produced_movies', to='movies.Person'),
        ),
        migrations.AddField(
            model_name='movie',
            name='production_designers',
            field=models.ManyToManyField(related_name='production_designed_movies', to='movies.Person'),
        ),
        migrations.AddField(
            model_name='movie',
            name='writers',
            field=models.ManyToManyField(related_name='wrote_movies', to='movies.Person'),
        ),
    ]
