# Generated by Django 3.1.5 on 2021-03-22 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_refactoring_movie_person_m2m_rels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
    ]
