# Generated by Django 3.1.5 on 2021-03-23 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_actors_moved'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Actor',
        ),
    ]
