# Generated by Django 3.1.5 on 2021-04-17 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsphoto',
            name='news_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='news.news'),
        ),
    ]
