# Generated by Django 3.1.5 on 2021-04-28 16:22

import ckeditor.fields
from django.db import migrations, models
import django_minio_backend.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_profile_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='news-images'), upload_to=django_minio_backend.models.iso_date_prefix),
        ),
        migrations.AddField(
            model_name='news',
            name='preview_title',
            field=models.CharField(default='-', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.DeleteModel(
            name='NewsPhoto',
        ),
    ]
