# Generated by Django 3.1.5 on 2021-05-05 16:23

import ckeditor.fields
from django.db import migrations, models
import django_minio_backend.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_news_content_to_rich'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='news-images'), upload_to=django_minio_backend.models.iso_date_prefix, verbose_name='Иллюстрация'),
        ),
        migrations.AlterField(
            model_name='news',
            name='preview_content',
            field=ckeditor.fields.RichTextField(verbose_name='Превью'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Заголовок'),
        ),
    ]
