# Generated by Django 3.1.5 on 2021-03-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_actors_moved'),
        ('person', '0003_refactoring_movie_person_m2m_rels'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='movies',
            field=models.ManyToManyField(related_name='persons', through='person.PersonRole', to='movies.Movie'),
        ),
        migrations.AddField(
            model_name='personrole',
            name='role_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
