# Generated by Django 3.1.5 on 2021-03-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_add_person_photo_rel'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='height',
            field=models.PositiveIntegerField(default=200),
            preserve_default=False,
        ),
    ]
