# Generated by Django 3.1.5 on 2021-03-22 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_refactoring_movie_person_m2m_rels'),
        ('person', '0002_add_height_to_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(choices=[('DIRECTED', 'Режиссер'), ('WROTE', 'Сценарист'), ('PRODUCED', 'Продюсер'), ('OPERATED', 'Оператор'), ('COMPOSED', 'Композитор'), ('EDITED', 'Монтажер'), ('ACTOR_IN', 'Актер'), ('PRODUCTION_DESIGNED', 'Художник-постановщик')], max_length=100)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.person')),
            ],
        ),
    ]
