# Generated by Django 3.1.5 on 2021-03-26 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_add_orientation_and_format_to_image'),
        ('person', '0006_add_orientation_and_format_to_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='surname',
        ),
        migrations.AddField(
            model_name='person',
            name='fullname',
            field=models.CharField(default='Nobody', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='ru_fullname',
            field=models.CharField(default='Никто', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personrole',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='movies.movie'),
        ),
        migrations.AlterField(
            model_name='personrole',
            name='role_type',
            field=models.CharField(choices=[('DIRECTOR', 'Режиссер'), ('WRITER', 'Сценарист'), ('PRODUCER', 'Продюсер'), ('OPERATOR', 'Оператор'), ('COMPOSER', 'Композитор'), ('EDITOR', 'Монтажер'), ('ACTOR', 'Актер'), ('DESIGN', 'Постановщик')], max_length=20),
        ),
    ]
