# Generated by Django 3.1.5 on 2021-03-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0007_person_name_refactoring'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='death',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='sex',
            field=models.CharField(choices=[('MALE', 'Мужчина'), ('FEMALE', 'Женщина')], default='FEMALE', max_length=6),
            preserve_default=False,
        ),
    ]
