# Generated by Django 3.1.5 on 2021-03-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0008_add_sex_and_death_to_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='fullname',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='height',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='personrole',
            name='role_type',
            field=models.CharField(choices=[('DIRECTOR', 'Режиссер'), ('WRITER', 'Сценарист'), ('PRODUCER', 'Продюсер'), ('OPERATOR', 'Оператор'), ('COMPOSER', 'Композитор'), ('EDITOR', 'Монтажер'), ('ACTOR', 'Актер'), ('DESIGN', 'Постановщик'), ('VOICE_DIRECTOR', 'Звукорежиссер'), ('TRANSLATOR', 'Переводчик')], max_length=20),
        ),
    ]
