# Generated by Django 3.1.5 on 2021-03-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0009_person_fields_to_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='fullname',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='ru_fullname',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='personrole',
            name='role_name',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
