# Generated by Django 3.1.5 on 2021-08-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0011_score_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='kp_id',
            field=models.PositiveIntegerField(default=1, unique=False),
        ),
        migrations.RunSQL('''UPDATE person_person SET kp_id = id '''),
        migrations.AlterField(
            model_name='person',
            name='kp_id',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
