# Generated by Django 3.1.5 on 2021-03-30 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='newsphoto',
            name='person',
        ),
        migrations.AddField(
            model_name='newsphoto',
            name='news_item',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='news.news'),
        ),
    ]
