# Generated by Django 3.1.5 on 2021-04-28 16:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_news_base_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='preview_title',
        ),
        migrations.AddField(
            model_name='news',
            name='preview_content',
            field=ckeditor.fields.RichTextField(default='-'),
            preserve_default=False,
        ),
    ]
