# Generated by Django 3.1.5 on 2021-01-17 12:57

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_change_score_related_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=5400)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='slogan',
            field=models.TextField(default='f', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.IntegerField(default=1994, validators=[django.core.validators.MinValueValidator(1895)]),
            preserve_default=False,
        ),
    ]
