# Generated by Django 3.1.5 on 2021-03-06 18:39

from django.db import migrations, models
import django.db.models.deletion
import django_minio_backend.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_add_movie_type_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(storage=django_minio_backend.models.MinioBackend(bucket_name='images'), upload_to=django_minio_backend.models.iso_date_prefix)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posters', to='movies.movie')),
            ],
        ),
    ]
