# Generated by Django 3.1.5 on 2021-03-27 07:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_add_orientation_and_format_to_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='age_rating',
            field=models.SmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxLengthValidator(18)]),
        ),
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='premiere',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='premiere_ru',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='rating_mpaa',
            field=models.CharField(choices=[('G', 'G'), ('PG', 'PG'), ('PG_13', 'PG-13'), ('R', 'R'), ('NC_17', 'NC-17')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='slogan',
            field=models.CharField(max_length=500),
        ),
    ]
