# Generated by Django 3.1.5 on 2021-05-20 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_score_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='created_at',
            new_name='updated_at',
        ),
    ]
