# Generated by Django 3.1.5 on 2022-09-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_kp_id_to_persons_and_movies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.DurationField(null=True, verbose_name='Продолжительность'),
        ),
    ]
