# Generated by Django 3.1.5 on 2021-04-17 14:41

from django.db import migrations, models
import django.db.models.deletion
import django_minio_backend.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_profile_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=django_minio_backend.models.MinioBackend(bucket_name='avatars'), upload_to=django_minio_backend.models.iso_date_prefix)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profilephoto'),
        ),
    ]
